### ISSUE TITLE
Sorting column has same values in all the row but still it sorts by another column

### ISSUE THREAD

**Issue by mjangir** [tannerlinsley/react-table#1310]
I'm using version 6 of react-table. I'm not really sure if its a bug or feature but as per my understanding how it should work, its a bug to me. The problem is, if one column of react table has same value in all the rows of the table, and we sort the table by this column, it still sorts but ideally shouldn't.

For example, there are 3 columns in the table (name, age, dob) with 10 records. If all the 10 people are of age 30, and we sort the table by age, it is sorting by name column. Ideally it should not do anything at all as data is anyway sorted.

**Comment by mrasal** [comment]
I am having the same Issue, Any solution for this?

**Comment by tannerlinsley** [comment]
This is called a stable sort. If values are the same, the order of the rows in the original data set are used to sort the data. This ensures that if you reverse rows that have the same value, they are inverted. This is expected functionality and is how enterprise datagrids should behave. If you want, you can use a custom sort function to disable this, but I wouldn't recommend it.

**Comment by meetDeveloper** [comment]
@tannerlinsley Could you give more insight, I am little confused a little about `ensures that if you reverse rows that have the same value, they are inverted`

**Comment by tannerlinsley** [comment]
Consider some data with three users: 
```js
const data = [
  { name: 'Bob', age: '2' },
  { name: 'Bob', age: '1' },
  { name: 'Bob', age: '3' },
]
```

Since all of the names are the same, if we sort by `name` the rows will collide by having the same name and eventually fall back to using the row index. The data will essentially look the same:
```js
const data = [
  { name: 'Bob', age: '2' },
  { name: 'Bob', age: '1' },
  { name: 'Bob', age: '3' },
]
```

If we click to sort again and invert the sorting, we would still run into the same problem, but this time, the row index is inverted, so we would get this sorted data set:
```js
const data = [
  { name: 'Bob', age: '3' },
  { name: 'Bob', age: '1' },
  { name: 'Bob', age: '2' },
]
```

Stable sort means that things are deterministic and always the same given the same dataset. It also means that row index is used as a fallback. 

To further explain why this is important, consider a similar dataset, but with a thousand records: 
```js
const data = [
  { name: 'Bob', age: '0' },
  { name: 'Bob', age: '1' },
  { name: 'Bob', age: '2' },
  ...
  { name: 'Bob', age: '1000' }
]
```

If stable sort wasn't used here, and row indices were ignored, it would either mean 2 things:
- Every time you resort this dataset by `name`, all of the Bob's would be randomly placed every time.
- You would never consistently be able to get to the top or bottom of the Bob's when sorted by `name`

Using a stable sort with index fallback ensures that all rows are treated equally and consistently.

**Comment by meetDeveloper** [comment]
@tannerlinsley Does it fallback directly to index or it also sort by any other column? Also you said `Every time you resort this dataset by name, all of the Bob's would be randomly placed every time.` why would that happen? Suppose you only use stable sort, but did not used index fallback, won't it solve this issue and the second one also? What is index fallback providing extra?

**Comment by tannerlinsley** [comment]
I think you misunderstood me. React Table **does use** a stable sort and **does fall back** to the index.

If multiple columns are sorted, then each row is sorted in that order, with the index used as the fallback at the very end.

> `Every time you resort this dataset by name, all of the Bob's would be randomly placed every time.` why would that happen?

Across browsers and node environments, `Array.sort` behaves differently. Some of them even have some level of "randomness" that happens when used on same-value sorting. For that very reason, React Table uses a stable sort with index fallback. That way, sorting will be the same across every browser and environment.

**Comment by meetDeveloper** [comment]
Does by fallback to index you mean, when no sort is applied? Actually I think I got confused a little back, and that is why maybe I am unable to grasp it.

**Comment by tannerlinsley** [comment]
When no sort is applied, the rows are displayed in the same order as the data array you pass React Table (sorted by original index).

If a sort is applied and multiple rows have the same sort value within that sort, those rows will fallback to sorting by that same original index order from the original array.
