### ISSUE TITLE
Column Widths Won't Enlarge

### ISSUE THREAD

**Issue by FlyRocketDrones** [tannerlinsley/react-table#1355]
I have a rather simple React Table like
       ```
 <ReactTable
          data={dataArray}
          columns={columns}
        />
```

Columns are not able to be enlarged when I click and drag, nothing happens.

**Comment by FlyRocketDrones** [comment]
This is the able:

```
        <ReactTable
          data={dataArray}
          columns={columns}
        />
```

**Comment by ShaiSaar** [comment]
There are resizing columns on V6.
no resizing columns on V7 with the hooks.
Are you planning to add it in this version?

**Comment by tannerlinsley** [comment]
We are working on it.

**Comment by FlyRocketDrones** [comment]
This issue is still active. Can you close it when you actually fix it?

**Comment by tannerlinsley** [comment]
It's not technically a bug or issue yet. It's in development and being tracked in PRs

**Comment by Graveheart** [comment]
@tannerlinsley Is there any progress on this feature for v7? It's the only thing that's preventing me from migrating to the new version right now.

**Comment by tannerlinsley** [comment]
There's been some work on this, but it's stalled because HTML tables don't support manual width resizing when there are multiple-headers (col-span conflicts). Technically you can do this on your own in your Table component without any extra stuff from React Table. You could even implement this pattern: https://www.brainbell.com/javascript/making-resizable-table-js.html, but you won't be able to use multiple headers.

We'll keep working on a drop-in solution though. It might take some time. This shouldn't discourage you from upgrading though. HTML tables are way better at automatic resizing that flexbox ever will be. With proper line breaks in your cell renderers when needed, you likely wouldn't need resizing for most use cases (but there are a few where you would)

**Comment by Graveheart** [comment]
Thanks for the fast response, Tanner. It's only for our big tables that we're still using v6 but I'll update them as well and try the solution you sent me since we aren't using multiple headers anyway.
