### ISSUE TITLE
Rendering too slow when 100's of tables renders in loop on same page

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [tannerlinsley/react-table#1356]
# Using v6?
v6.8.6

**Describe the bug**
React table is rendering too slow. I have more than 100 accordions on the page where each accordion render the react table once expanded. I have added option to expand all accordions at a time. So when all accordion are expanded at the time all 100 table gets rendered which causing issue. all expanded tables get rendered after 4-5 seconds.

**Expected behavior**
all tables ie 100 tables on the page should get rendered at time and quickly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by manigandham** [comment]
100 tables is a lot to render and it depends on many factors including how much data you have and the browser and CPU of the device being used.

You should probably look into lazy loading the tables that are actually in view instead of all of them, or load them in batches so the page stays responsive. Javascript is single-threaded and you'll have issues trying to do so much processing and rendering all at once.

**Comment by tannerlinsley** [comment]
@manigandham is correct. This is not an issue with React Table. You are trying to render to much on the page at once. I would suggest virtualizing the rendering of each table to only display it when it is in or near the viewport.
