### ISSUE TITLE
Chore: Commitizen and lint-staged/prettier are not working in the correct order.

### ISSUE THREAD

**Issue by tannerlinsley** [tannerlinsley/react-table#1410]
@larrybotha  Would love a second pair of eyes on this.

**Comment by larrybotha** [comment]
What's happening?

This is what should happen:

- make changes
- stage changes
- `npm run commit`
- enter commit details via prompts
- pre-commit hook runs after details are entered, processing files, and adding changed files to commit

**Comment by tannerlinsley** [comment]
Can you give it a try! Add some comments or something and test out the process. May move and update the contributing section in the readme to a contributing.md file?

**Comment by larrybotha** [comment]
Working for me:

![960](https://user-images.githubusercontent.com/1510520/61972084-4b0bb080-afa6-11e9-9a39-efc22fa20dc0.gif)

Do you have a different workflow that is resulting in something unexpected?

**Comment by tannerlinsley** [comment]
Hmm. I see now. Here's what I'm thinking, let me know you're thoughts:

- I'd like to enforce commitizen, using something like the `pre-commit` hook
- I want to make it obvious and easy what's going on for users who use something like the Github app or the Fork app

How would we do that?

I started trying to set that up and that's when the formatting and staging order got switched around?

**Comment by larrybotha** [comment]
hmmm ye, you can add

```javascript
	'prepare-commit-msg': 'exec < /dev/tty && git cz --hook'`
```

to `.huskyrc.js`, but it creates problems with GUIs because they may not have an interactive terminal (`exec < /dev/tty`) - I tried fixing a merge conflict using SourceTree now and it rejected the commit.

Looks like it doesn't work on Windows, either: https://github.com/commitizen/cz-cli/issues/627

Probably better to reject a commit message if it doesn't follow a specific convention; something like `commitlint` is likely the best way to do that:

https://github.com/conventional-changelog/commitlint

**Comment by tannerlinsley** [comment]
Yeah, that's probably best.
