### ISSUE TITLE
Suggestion: Use gitdown

### ISSUE THREAD

**Issue by gajus** [tannerlinsley/react-table#1441]
Just a suggestion: use gitdown (https://github.com/gajus/gitdown) to generate readme.

It is getting really long and there are some broken links. Gitdown can help with that by breaking a long README into multiple files and finding broken links.

See https://github.com/gajus/slonik as an example of library that uses gitdown. README source files are in `.readme` directory.

**Comment by tannerlinsley** [comment]
I've used gitdown before and while I personally thought it was pretty nice, I decided it's not something I wanted to place on contributors to understand or meddle with. The plans before release for the docs are:

- Split the Readme into separate directories/pages
- Move link declarations to the bottom of each page and reference them instead of inlining them.

Thanks for the suggestion though! I'll continue to consider it during the docs reorganization.
