### ISSUE TITLE
setting and changing pageIndex through a prop does not re-render

### ISSUE THREAD

**Issue by rparree** [tannerlinsley/react-table#1468]
Hi,

I am trying to make the current page bookmarkable using a query param for the page number. However when i update the prop,the table does not re-render.

Here is a codesandbox: https://codesandbox.io/embed/rparreereact-table-pagination-query-params-7kd0p

- In `App.js#41` i am setting the `pageIndex` based on the `currentPage` prop
- This prop gets set/changed by the main `App` component using a query string

The value of the `currentPage` does change, but not the `pageIndex`.

p.s. original post on spectrum:  https://spectrum.chat/react-table/general/setting-and-changing-pageindex-through-a-prop~50cb10b7-b3af-4444-8227-e9a3bbedd3a9

tx.,

**Comment by ShareefAlawneh** [comment]
I believe that you are not doing it right, in your example, what you do is you pass the pageIndex in the initial state, which filled once, otherwise, you should but you updated data in the overrides as `const tableState = useTableState({}, { pageIndex: currentPage });`,
more information about `useTableState` in https://github.com/tannerlinsley/react-table/blob/master/docs/api.md#useTableState

**Comment by tannerlinsley** [comment]
☝️This is correct

**Comment by marcofriso** [comment]
I had the same issue, in my case I had to replace ` defaultValue={pageIndex + 1}` with `value={pageIndex + 1}`
