### ISSUE TITLE
[QUESTION] How to change responsibilities of header rows ?

### ISSUE THREAD

**Issue by sinout** [tannerlinsley/react-table#149]
Hi,
I'm trying to render data with your library and I have one question. How can i make `1st` header row to be sortable and the`2nd` to render custom components. 
By this time `1st` row is disabled and only `2nd` is sortable. 
So in general I want the `1st` header row to be responsible for data sorting and `2nd` to be just additional row with custom components.
![screenshot](https://cloud.githubusercontent.com/assets/8354561/24432312/f7d62c70-1429-11e7-850e-7c47f764cb79.png)

**Comment by tannerlinsley** [comment]
This would require overriding the built-in components (https://github.com/tannerlinsley/react-table#component-overrides).  It would require just a tiny bit of work, but essentially you would want to basically copy the default components for header and header groups, but swap the sorting event handlers from the normal header to the header group.  Not sure how involved this is, but theoretically, that's what needs to happen.

Closing for now, since this is not a supported option right now, but technically is feasible.  If you are able to get it to work, be sure to post your solution here!
