### ISSUE TITLE
react-table-v6 package link broken

### ISSUE THREAD

**Issue by dmarkow** [tannerlinsley/react-table#1613]
I'm trying out the v7 beta, but still need access to v6 for some existing components. The updated README links to [react-table-v6](https://www.npmjs.com/package/react-table-v6) which doesn't exist. It looks like [@kizu/react-table-v6](https://www.npmjs.com/package/@kizu/react-table-v6) is the correct package.

Not sure if the README needs to be fixed, or if the package wasn't supposed to be namespaced under @kizu?

**Comment by kizu** [comment]
I think @tannerlinsley is probably on vacation, so that is probably why the proper package wasn't yet published.

I've published the `@kizu/react-table-v6` to be able to use it this way in the meantime, but I'd prefer to use the official channel as well. So I guess we just need to patiently wait for @tannerlinsley to came back; rest is important, so I guess no hurry!

Glad to see that I'm not alone in this case and that this would be useful for others who would need to use both v6 and v7!

**Comment by tannerlinsley** [comment]
I'm back! I'll try and get this done by the end of the week. Thanks for holding the fort down while I was away!

**Comment by tannerlinsley** [comment]
The link should be back to normal. We had to use react-table-6 instead since someone had already published over react-table-v6.
