### ISSUE TITLE
Produced HTML tags unnecessarily have empty class attribute

### ISSUE THREAD

**Issue by yvanzo** [tannerlinsley/react-table#1618]
# Using v7.0.0-beta.12

**Describe the bug**
Tags (`table`, `thead`, `tbody`, `tr`, `th`, and `td`) are produced with needless `class=""` attribute when no `className` is added.

**To Reproduce**

1. Go to any example, such as  [basic](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/basic) example.
2. Examine any cell using inspector
3. See `class=""` in produced HTML code

**Expected behavior**
There should not be any `class` attribute when no `className` is added.

**Comment by Jeanmsilva89** [comment]
I'm also noticing that if I add a className property to the column, it still doesn't add that className to the cell or header cell. 

```{
            Header: "First Name",
            accessor: "firstName",
            className: "testClass",
            headerClassName: "testClassHeader"
          }```

Should add the className to the cells under the firstName column,  however it doesn' seem to add anything. 

https://codesandbox.io/s/tannerlinsleyreact-table-basic-classname-fvj4o?fontsize=14

Let me know if you are seeing the same behavior, if so perhaps it can be fixed in this PR? I'm happy to submit a PR as well. 

Cheers

**Comment by tannerlinsley** [comment]
This is not something that is built in to react table. Though it's easy enough to implement in userLand by simply referencing any `className` or `style` property defined on the column when rendering and placing it on any element you wish.
