### ISSUE TITLE
Pagination doesn't change on data change

### ISSUE THREAD

**Issue by eladbs** [tannerlinsley/react-table#165]
## Problem Description
I have a text input to filter the array of data I pass to ReactTable.
If I have `defaultPageSize={5}` and the initial data array has 20 elements then I have 4 pages to paginate through.
Now, let's say I go to page 3 in the table and then type into the text input and filter out 18 items - I left with 2 items in the data array I pass to ReactTable. 
The problem is that the table stays in page 3 and the pagination data is wrong at this state.

As far as I see it, every time the data array that is passed to ReactTable changes the Pagination component should update with current data and go to the beginning - page 0.

![2017-04-03 11_06_04](https://cloud.githubusercontent.com/assets/1691671/24600777/cc1c8168-185e-11e7-8a33-255f065189d2.png)

Thanks a lot!

**Comment by eladbs** [comment]
Funny thing is that I just found the solution after 2 days I'm struggling with it...

I use the onPageChange callback to handle the "page" prop and when I filter I always reset "page" to 0.

**Comment by TacticalCoding** [comment]
I just wanted to let you know that while your solution works, what you're seeing sounds very similar to this ticket https://github.com/tannerlinsley/react-table/issues/159 which has since been fixed in version 5.4.1.

There is a slight difference though because it will take you back to the last page available instead of resetting it to 0.

**Comment by eladbs** [comment]
I didn't know about your fork. I was looking at the releases here and assumed I have the latest version.
My fault.
I upgraded to latest version and everything works as it should out of the box.
Thanks for the reply and info!!!!

**Comment by yolohello12** [comment]
@eladbs Hi, I ran into the same issue. Can you please elaborate what exactly you did to solve this or share an example?

Thank you,

**Comment by eladbs** [comment]
@yolohello12 
My solution was keep the current page in the parent component and to "reset" the it to one when the data was changed externally.
But it was fixed already in the version mentioned above.

**Comment by anshul1488** [comment]
Hey, I am getting the same issue here in my code. Could some one provide a working example with this issue fixed. This issue is replicable in the controlled component example on react table site, my example is something very similar but gets data from server.
https://codesandbox.io/s/r7xezrk2?from-embed

thanks.

**Comment by fifovillage** [comment]
yeah this is not good

**Comment by gajendrapratap** [comment]
> Funny thing is that I just found the solution after 2 days I'm struggling with it...
> 
> I use the onPageChange callback to handle the "page" prop and when I filter I always reset "page" to 0.

can you provide the code snippet for reference.
