### ISSUE TITLE
"Kitchen Sink" example, search on any page other than the first you potentially get no results

### ISSUE THREAD

**Issue by victorthevong** [tannerlinsley/react-table#1652]
In the current "Kitchen Sink" example code sandbox. Go to any page that isn't page 1 (let's say page 3) and search lets say "cry" nothing appears and the page number below is 3 out of 1. Search seems to only work on the first page 100% of the time and only works thereafter assuming the search result number of pages is greater than the current page starting the search. i.e 1 out of 1 compared to 3 out of 1. Where "cry" appears on page 3 where I initiate the search, but search results for "cry" is only 1 page hence blank results.

**Comment by tannerlinsley** [comment]
I cannot replicate this. When filtered rows result in less pages than the page index you are currently on, the page index is clamped to the new maximum of pages available. Also, when filtering is applied, it shouldn't be running into this problem anyway, since filtering results in a new row model under the hood, which in turn, automatically resets the page Index to 0.

If you believe this is still an issue, please open a new issue with a forked codesandbox link that can easily replicate the problem every time with specific instructions.

Thanks!
