### ISSUE TITLE
documentation error for disabling column sorting

### ISSUE THREAD

**Issue by terebentina** [tannerlinsley/react-table#1656]
# Using v6?

no

# Using v7?

yes

**Describe the bug**
The documentation for [disabling the sorting](https://github.com/tannerlinsley/react-table/blob/master/docs/api.md#column-options-1) of a column mentions `disableSortBy` as the prop to use, however that doesn't seem to do anything. It seems that `disableSorting` has the desired effect. So either the docs or the code will have to be fixed, not sure which one.

**Comment by androsj** [comment]
@terebentina It was changed to disableSortBy on the latest version (beta.14)

**Comment by tannerlinsley** [comment]
Yep. You must upgrade to use `disableSortBy`. `disableSorting` was renamed in the latest release.

**Comment by ibrkljacic** [comment]
@tannerlinsley Is there updated documentation with all the updated props? It's nowhere to be found.
I'm using the latest v7 version and I spent the whole day trying to make `disableSorting` work. If there weren't for this issue here, I wouldn't find the solution and would probably find some other table library to use. Please add updated documentation with all the props listed !! :)
