### ISSUE TITLE
two state sort?

### ISSUE THREAD

**Issue by yigalirani** [tannerlinsley/react-table#1691]
I am looking at the sort example, clicking a column header toggles between three state: sort up, short down and unsorted.

Is it possible to have the click toggle between 2 states only:  sort up and sort down?

**Comment by tannerlinsley** [comment]
Please take a look at the docs here: https://github.com/tannerlinsley/react-table/blob/master/docs/api.md#useSortBy

Search for the `disableSortRemove` option.

**Comment by vjwilson** [comment]
I tried adding `disableSortRemove` to a table that uses server-side pagination, because it wasn't triggering a new sort event when you clicked on a header that was already sorted ASC.

If you click the header again, it does fire a sort event and we toggle to a DESC server side call.

If you click while it's already DESC, it fires a sort event and we toggle to an ASC server side call.

(We are still using v6 of react-table.)

**Comment by juliolopeztorres** [comment]
> Please take a look at the docs here: https://github.com/tannerlinsley/react-table/blob/master/docs/api.md#useSortBy
> 
> Search for the `disableSortRemove` option.

Just to update the docs. I faced the same issue today and working properly after adding the `disableSortRemove` flag when `useTable()` call.

[disableSortRemove DOC](https://react-table.tanstack.com/docs/api/useSortBy#table-options).

Thanks.
