### ISSUE TITLE
[V7] Skip resetting of useRowSelect and usePagination hooks

### ISSUE THREAD

**Issue by Ksoso** [tannerlinsley/react-table#1702]
I'm in process of migrating my React App to react-table v7. I have got my application state in Redux and i need to do some preparations to put my data into table. The problem is I don't want to keep ressetting row selection and pagination state every render.

I followed example from: [Kitchen Sink](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/kitchen-sink) and I keep my own skipReset value in my Redux Container component which render table with data. The problem is I get a warning in console like:

> Warning: The final argument passed to useEffect changed size between renders. The order and size of this array must remain constant.

You can observe it also in Kitchen Sink example on codesandbox by simply edit cell value and save it.

**Comment by tannerlinsley** [comment]
This is likely because you are returning a different number of dependencies in of the `getReset___Deps` options. If you are running into that, I would try passing the same number all the time with `null` placeholders (which won't trigger a reset), but then "turn them on" by setting them to a normal dep when you need to use them which will trigger a reset when they change), eg.

```js
useTable({
  getResetPageDeps: instance => {
    const pageResetEditing = isEditing ? null : instance.rows
    const pageResetEditing = isUpdating ? null : instance.rows
    return [pageResetEditing, pageResetDataUpdating]
  }
})
```

Let me know if you have more questions or run into anything unexpected.

**Comment by tannerlinsley** [comment]
This discussion happening right now is relevant to this issue: https://github.com/tannerlinsley/react-table/issues/1729

I would appreciate your feedback on it.
