### ISSUE TITLE
can not make column with fixed width and table with full width (100%).

### ISSUE THREAD

**Issue by OlegBrony** [tannerlinsley/react-table#1747]
# Using v7?
yes

**Describe the bug**
the root problem. I have server pagination and when I go to next page (which basically just puts other 'data' prop) the table columns are 'jumping'.
What I want to do: table with full width (100%) and add an ability to add 'width' prop to columns.
I tried to paste useBlockLayout, but it's only ruin everything. 
is it possible?
I also tried to find some example, but I didn't find this case in [this](https://github.com/tannerlinsley/react-table/blob/9829927fab8f300dbceb83fd58393a263a41a7f7/docs/examples.md) page.

**Screenshots**
![image](https://user-images.githubusercontent.com/19880334/70514228-e8bde180-1b3b-11ea-9c5a-94f05122875f.png)
![image](https://user-images.githubusercontent.com/19880334/70514285-055a1980-1b3c-11ea-8bea-2b2d30bb24a4.png)
![image](https://user-images.githubusercontent.com/19880334/70514404-43efd400-1b3c-11ea-8ccb-7c4a39f24e40.png)
![image](https://user-images.githubusercontent.com/19880334/70514419-4b16e200-1b3c-11ea-88db-3029a4b21826.png)

**Codesandbox!**
https://codesandbox.io/s/still-sky-s4ye7

**environment**
doesn't matter.

**Comment by tannerlinsley** [comment]
When you say a full-width table, but with static column widths, you are referring to something that is technically a bit contradictory to one-another. A full-width table must know how to shrink/grow columns dynamically, which means they cannot be static width all the time.  The only advice I can give you would be to render your table using actual table elements (and not the useBlockLayout hook) with all columns having a static width except for the last column, which you can set to be some kind of small percentage width and hopefully it will "grow" to fill the rest of the table.

Seeing how React Table has very little to do with styles and layout these days means that I don't have an answer to this question that will work for everyone the same way 100% of the time.

You can start by looking at this example I gave someone a while back which does something similar, but with collapsable columns instead of static width ones. It may inspire you on how to achieve what you want:

https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/full-width-table

**Comment by tannerlinsley** [comment]
Feel free to comment with more info/questions, but going to close this for now.
