### ISSUE TITLE
A way to pass something to a propGetter inside render

### ISSUE THREAD

**Issue by kizu** [tannerlinsley/react-table#1791]
One thing I've noticed I miss when using the propGetter hooks and the propGetter like `getRowProps` in the render of my table is a way to pass any params to the getter, in a way those would be accessible from any defined getter.

Example of such param that is not available in the instance: `index` — when we want to add some props based on the element index in the DOM, right now the only way is to do this in the render. However, this is something plugins would like to utilize.

On the propGetter in the render side this should be quite simple: it currently accepts one argument, so we can allow passing all the options we need as the second param.

On the propGetter hooks side things are a bit more complicated I think, as they already accept two or more arguments. So if it could be added there, I imagine it could go as a second argument, right after props, moving the instance to the third and contextual ones further?

Alternatively, maybe the API of the propGetter plugin hooks could be interfaces instead of lists of arguments? So instead of current `(props, instance, context) => props` it could be `({ props, instance, context }) => props`, and this would allow us to add anything there in a way it would be easily accessible? Adding a fourth named param to the interface this way would be much easier, it could become just `({ props, instance, context, arguments }) => props` or something similar.

**Comment by tannerlinsley** [comment]
I see, so you want to be able to access things from `row.getRowProps({ index })` in the propGetter hook: `({props, instance, row, userProps }) => [props, { key: index }]`?

**Comment by kizu** [comment]
Yep, something like that! Would make it possible not only to override everything with user props, but use those as defaults or to control some stuff in the getters at the render level.

**Comment by tannerlinsley** [comment]
Okay. This will be yet another breaking change to the RC, but I think it's a good one. Personally, I think I would like to go with this signature:

```js
hooks.getRowProps.push(
  (previousProps, {instance, namedContexts, ...userProps }) => PropGetterReturnType
)
```

That way it keeps the "reducer" vibe.

**Comment by tannerlinsley** [comment]
And luckily it will only be breaking for plugin devs. Table renderers should be backward compatible.

**Comment by tannerlinsley** [comment]
Do you think you'll want to be able to manipulate user props? Eg. if a user passes a prop, would you want to be able to remove it so it doesn't override your own?

Is this sufficient?
```js
hooks.getRowProps.push(
  (props, {instance, row, userProps, userProps: { myNum } }) => {
    delete userProps.key // So their prop doesn't override our own
    return [props, { myNum: myNum + 1 }]
  }
)

row.getRowprops({ myNum: 5 })
```

**Comment by kizu** [comment]
Yep, this looks good!

**Comment by tannerlinsley** [comment]
## 7.0.0-rc.14

- Changed the function signature for all propGetter hooks to accept a single object of named properties instead of a variable length of arguments. The user props object has also been added as a property to all prop getters. For example, `hooks.getRowProps.push((props, instance, row) => [...])` is now written `hooks.getRowProps.push((props, { instance, row, userProps }) => [...])`

**Comment by tannerlinsley** [comment]
Updated: 

## 7.0.0-rc.14

- Changed the function signature for all propGetter hooks to accept a single object of named meta properties instead of a variable length of meta arguments. The user props object has also been added as a property to all prop getters. For example, `hooks.getRowProps.push((props, instance, row) => [...])` is now written `hooks.getRowProps.push((props, { instance, row, userProps }) => [...])`
- Changed the function signature for all reduceHooks accept a single object of named meta properties instead of a variable length of meta arguments. For example, `hooks.flatColumns.push((flatColumns, instance) => flatColumns)` is now written `hooks.flatColumns.push((flatColumns, { instance }) => flatColumns)`
- Changed the function signature for all loopHooks accept a single object of named meta properties instead of a variable length of meta arguments. For example, `hooks.prepareRow.push((row, instance) => void)` is now written `hooks.prepareRow.push((row { instance }) => void)`

**Comment by tannerlinsley** [comment]
Released!

**Comment by kizu** [comment]
Great, would try to look at it tomorrow!
