### ISSUE TITLE
useAbsoluteLayout and MUI

### ISSUE THREAD

**Issue by The-Code-Monkey** [tannerlinsley/react-table#1792]
# Using v7?

I am using 7.0.0-rc.12

**Describe the bug**

Unable to use `MUI` and `useAbsoluteLayout` as it causes the heights of the columns to be lost and its not a simple fix as far as i am aware.

**To Reproduce**

https://codesandbox.io/s/fervent-banzai-8pe55

comment in `useAbsoluteLayout` to see the issue

**Expected behavior**

Should just allow me to change the widths of columns

**Desktop (please complete the following information):**

issue not browser or device specific

**Comment by tannerlinsley** [comment]
This is because MUI tables use HTML table elements, not divs and styles. To use an absolute layout, you would need to either (1) use divs instead of table elements or (2) switch all of your table element styles to be `display: block` (`display: inline-block` for cells) and last but not least, when using an absolute layout, your rows must have a predefined height, eg. 50px.

**Comment by tannerlinsley** [comment]
Feel free to comment with more questions. Thanks!

**Comment by The-Code-Monkey** [comment]
I feel like this should either be handled by `useAbsoluteLayout` or at least documented as a case specific tweak as it wasn't obvious to me what the issue was at first.

**Comment by The-Code-Monkey** [comment]
@tannerlinsley see updated example of what is still issues regarding this https://codesandbox.io/s/fervent-banzai-8pe55
