### ISSUE TITLE
Inline cell editing for different data types

### ISSUE THREAD

**Issue by rajaraodv** [tannerlinsley/react-table#183]
Please add support for inline editing cells w/ different types of data (input, calendar, menu etc)

**Comment by tannerlinsley** [comment]
This is already possible, thought due to the number of ways this can be approached (and the integration necessary with so many different state management and usage scenarios, we have not yet included this in the core.  If you would like to discuss how this is done, please join the slack organization).  If and when a suitable API and implementation for this is reached that satisfies the 90% use case, we will consider adding it as a core feature.  In the meantime, we suggest contributing to the wiki with more information on how to achieve this. :)

**Comment by rajaraodv** [comment]
cool thanks!
