### ISSUE TITLE
Drag n' drop pivoting

### ISSUE THREAD

**Issue by rajaraodv** [tannerlinsley/react-table#185]
I have seen many libraries provide a cool capability that allows grouping by dragging column header to a row above. 
See: https://ag-grid.com/example.php

**Comment by tannerlinsley** [comment]
What you are referring to as "grouping" is also known as pivoting, which technically react-table supports, but not via dragging the column header.  This is also another feature that technically could be implemented right now, but would be very involved and probably require much work with custom components.  

This probably relies heavily on #184 and what we decide to do there.
This state is also something that I believe should be forced into a user-maintained state (eg. we won't manage the state internally, since we would have to create a new interface for managing that state.)

This is definitely a valid feature request, but likely will not fall into the core pipeline in the near future.  I would suggest drafting a solution or recipe for the wiki to outline how this could be achieved using the existing API
