### ISSUE TITLE
type of the "indeterminate" prop

### ISSUE THREAD

**Issue by askesis** [tannerlinsley/react-table#1891]
Version 7.0.0-rc.11
Chrome 80.0

Have a question. Should "indeterminate" be fixed in this package or in the @types/react-table or it is not a mistake at all?

https://github.com/tannerlinsley/react-table/blob/b1b71103c4be32e16a9c9886d685008a33fd6dd6/src/hooks/useColumnVisibility.js#L57

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f44f31789c08ce190cf58b0d441977dabb968f24/types/react-table/index.d.ts#L83

**Comment by tannerlinsley** [comment]
`indeterminate` is not a supported prop in React for many reasons, but it is a useful prop that your checkbox component should be utilizing. Simply destructure it from props and use it in an effect like [here](https://github.com/tannerlinsley/react-table/blob/master/examples/row-selection/src/App.js#L37-L43). Do not try and place it on an `input` element, since it is not supported by react.
