### ISSUE TITLE
Make v7 retrocompatible, or continue support for v6.

### ISSUE THREAD

**Issue by marcosandri-dev** [tannerlinsley/react-table#1897]
Hello. 

I'm not using any of the tools or anything else provided to make requests or whatsoever. What I am writing here is a statement against this new version of this library, because frankly, developers should not be put in a condition of working with the only tool available but that are dependent by people who don't care about what has been done by other people.

This library has 300k downloads per day, and that's huge. Actually, since the v7 was released, it got less friction, and I think that's a direct consequence of how hardly implemented this new version is.

It's beautiful that someone has put his time and effort into something that other people are now using actively. 
But it's also terrible when, being dependent by a technology done by the community (in this case two people apparently), a developer should be forced to change ALL its codebase to make it work with a newer version because the old one is not supported anymore from one day to the other.

I understand that one wants to make everything better, but at a certain point creators have to understand that they cannot simply do what they want with a product that is now used by thousands of people, that bad choices have consequences, and this statement is one is it, for how much one can try to avoid it.

Moreover, this library assumes now that you are a react/javascript expert, which applies to at least the 10% of us, and even so, they should be able to understand how all of this works without a very good documentation, which is really required for a project like this.

I think that many other developers are struggling as I do, and will eventually abandon using this library, and I actually suggest them to do it, because nobody should trust someone that decides to make something this opinionated out of nowhere.
A project needs responsibility and joint work, and here I see none (not even a migration guide!), so with all the good intentions behind a project like this, I will warmly suggest everybody who's running a business to not use it anymore.

I am now looking for better alternatives, but since this package has dominated "the market" until now, there aren't many. v6 was a breeze. Now I am avoiding refactoring all my codebase, keeping the v6 until I don't find a new good solution.

It would be awesome to either continue the v6 support or to make v7 retrocompatible and I'll be happy to help with it, but since this is just a very big rant (I'm sorry, but it may have bad consequences for my job) it will probably just go into the trash bin.

I hope at least the creators see it, and ask theirselves if they really made the right decision, because I also think they are smart enough to make something that everybody could use and enjoy. Until that time, farewell.

**Comment by arwandar** [comment]
I would like to add that it is not very responsible to stop supporting v6 when v7 is only in beta, and that from one version to another, there are still breaking changes, so v7 is not mature.

thanks @marcosandri-dev  to show my feelings about how this project now live

**Comment by marcosandri-dev** [comment]
> I would like to add that it is not very responsible to stop supporting v6 when v7 is only in beta, and that from one version to another, there are still breaking changes, so v7 is not mature.
> 
> thanks @marcosandri-dev to show my feelings about how this project now live

They/He is not going to make it retro-compatible, he didin't even provide a migration guide. He just decided that a library used by a thousands of people could have had breaking changes from one version to another without taking in consideration all the consequences of his decision. V6 wasn't the best library, but V7 is impossible to use in its state, so you don't have a stable version to go on with. 
Moreover, he doesn't seem to dedicate the appropriate time to it, and when you want to be the sole responsible of a project you have to, at least, put that in consideration. But he didin't, so people like me or anybody else is now struggling.

**Comment by kizu** [comment]
V7 is totally usable in its current state. Yes, it is in RC state, and as things are smoothing out, there are sometimes breaking changes, but that is the point of alpha/beta/RC — to see if there are problems with the library before the version is fixed. When the proper 7.00 version would be released, we can expect not to have breaking changes.

Another thing I need to say: this is an open source project, we can't expect for maintainers to be always working on it, there can be other priorities. If you want for things in a project to move faster — you can always go and [sponsor the author](https://github.com/sponsors/tannerlinsley), this would allow to prioritise the development of the library over other things, even if so slightly.

Also, it is strange to expect v6 to be maintained when there is even not enough time to work on v7 full-time. If someone wants to step-in into maintaining v6 — great! If you'd create PRs to its branch, would show that you know the codebase, would make sure to test everything — I can see you becoming a co-maintainer of the v6 part. You can also first fork it, work on it separately and then see if this work could be released officially.

We're lucky to have these wonderful projects in open source and to benefit from them. We should be more grateful and be less demanding.

**Comment by marcosandri-dev** [comment]
I totally get the open source and everything, and I am grateful yes (even if there is a certain amount of good stuff that you can get by showing how successful an open source project of yours is); I never questioned that, and I have also stated that "It's beautiful that someone has put his time and effort into something that other people are now using actively."

But, when an open-source project is used by people and businesses, not everybody has the time and capacity to change stuff related to that. Imagine doing that with all the libraries you would use because "why to reinvent the wheel?". I don't even actually want to sponsor something that I am not going to use anymore - it has taken less time to rebuild a table component by my own then trying to use this one, and I don't even want to be a co-author of something that I have not created and that's not followed anymore - it is not my responsibility, and if I have to do it, I will probably adapt the solution to solve my actual problem rather then creating something that's going to be used by everybody, like, just for fun. And there is already a react-table v6 npm, so I cannot even take pride out of that.

And please stop with the "don't be demanding" rhetoric. You cannot pretend that everybody using this library is just doing it in its free time and for fun. I think one could take pride of the fact that this is used as a main part of their business projects - being the most demanded and used react-table library - and one cannot just shrug off any critique by simply stating that. From "great power comes great responsibility", and I think at least one should look up to their errors rather then saying "you're too demanding", and that are, again: 

- Not having provided a proper migration guide;
- Not having provided a proper API documentation for the not JS experts;
- Having not supported the old version up to deep breaking changes;

These things will make devs struggle **really** a lot; one now may have 15-20 react-tables or more used in their web-apps, and they will have to refactor them without having a clue, and so they will probably have to dedicate weeks to rewrite them with the new logic and hoping that nothing breaks, and testing them, and so on and so forth. 

Realize at least the impact of your choices, since company bosses _are_ demanding, and libraries are tools that should makes devs lives easier; I am not pretending you will do something out of this closed issue, even because I'm developing my own solution right now, but really, listen to the critiques. Good luck.

**Comment by kizu** [comment]
If someone is using an open source for business, then the business should sponsor the development of the libraries. Otherwise it is just corporations getting an immense value from people maintaining their projects mostly for free.

v7 is so drastically different from v6 that there can't really be a proper “migration guide”. BTW, I'm not a library maintainer, I'm just a developer who have a codebase right now both with v6 and v7, slowly migrating existing tables to v7. It is pain, but v7's API makes it very easy to implement anything additional to what we have. Looking at the API of both v6 and v7, I can see how there is no real point in maintaining v6 and adding new features to it (except for potential very serious bugs and security flaws). The approach of v7 is so much better that even though I'm spending a lot of time migrating old v6 tables to v7, the result is so much better because v7 is so powerful and pluggable.

And it is much easier to support or to fix stuff by ourself — using forks, `patch-package` and so on — it is very easy to not wait for the fixes to be properly released before using them or writing them for your cases.

And last thing: if v6 works for you, I'm not sure why would you want to migrate for v7, as this is really a very different approach. The idea of keeping the deps green “just to be on the latest version” is not productive.

**Comment by VincentLanglet** [comment]
A huge +1 @marcosandri-dev.

This v7 is juste like a new repository, still without a production ready version, and with nothing, absolutely nothing in common with the previous version. So if, as said in the README and in your messages, the codebase is (almost) completely different, this would have been better to create a new repository like `react-table-hooks`, keep it separated from this repository and looking for maintainers if the author doesn't want/doesn't have time to provide support.

**Comment by tannerlinsley** [comment]
Hello everyone! Core maintainer, builder, life-juice of this library here. 

I don’t have as much to say as you do on this subject mostly due to time but also because I don’t personally enjoy entertaining attitudes of entitlement.

So I’ll keep it brief.

- If you don’t like v7, don’t use it. This is not a product you pay for and unless you are a sponsor or have actively contributed to the project then I won’t tolerate demanding tones for long term support from leecher-types. 
- If your business depends on v6 and you don’t want to sponsor v7, then you are more than welcome to fork v6 and dump your own company’s money into it’s long term support or better yet, convince me to let you maintain react-table-6 and become a real contributor. I must warn you though, you will likely eventually run into the same issues I did with maintenance, support, and architecture and possibly abandon it or resolve to rewrite it (you could even use v7 to do that). Your move.
- Don’t assume that any decisions I’ve made are I’ll informed, shallowly thought through or careless. I know 100x more about this project than most and likely use it 10x more than most. I understand it’s strengths, weaknesses, position within the “market“ and ultimately what is best for its future and until you own a share of it either through merit or money, you have no right or even precedent to exhibit the attitudes in this issue. I invite anyone who is sympathetic to this attitude to re-examine your feelings of entitlement.
