### ISSUE TITLE
Behaviour of expanded rows has changed when sorting columns in v7.0.0

### ISSUE THREAD

**Issue by carlosrberto** [tannerlinsley/react-table#2030]
I started using react-table on `v7.0.0-rc.15` and I noticed that the behaviour changed when we have rows with subRows and we sort a column.

It seems that it is now sorting each subRow separately.

For example if I have the following table where `R1.1` and `R1.2` are subRows of `R1`:

| Row  | Value |
|------|-------|
| R1   | 4     |
| R1.1 | 7     |
| R1.2 | 3     |
| R2   | 6     |

If I sort ascending by `Value` column using version `v7.0.0-rc.15` I get the following result:

| Row  | Value |
|------|-------|
| R1.2 | 3     |
| R1   | 4     |
| R2   | 6     |
| R1.1 | 7     |

But using version `v7.0.0` the result will look like:

| Row  | Value |
|------|-------|
| R1   | 4     |
| R1.2 | 3     |
| R1.1 | 7     |
| R2   | 6     |

You can see the difference here:

Using `v7.0.0-rc.15`:
https://codesandbox.io/s/expandsort-m4gp0

Using `v7.0.0`:
https://codesandbox.io/s/new-sort-expand-wvxgn

My question is how can I have the same result from `v7.0.0-rc.15` using `v7.0.0`?

**Comment by tannerlinsley** [comment]
This mostly has to do with the new restriction that useExpanded must now come after useSortBy. This is intentional, as it doesn't make much sense to first expand rows into a flat structure, then sort them. If that was the case, then there wouldn't be much sense in nesting them in the first place. That said, if you do indeed have a use case for this, then i would suggest that you look into creating your own version of useSortBy and possibly even useExpanded to match it. They are plugin hooks after all and can be swapped for whatever custom functionality you want!
