### ISSUE TITLE
Select row using Virtualized Rows (React-Window)

### ISSUE THREAD

**Issue by vsSanti** [tannerlinsley/react-table#2090]
**Bug description**
Using a table with virtualized rows and row selection, when clicking on the checkbox to select said row nothing changes on DOM, although changes on state.

[Link to codesandbox](https://codesandbox.io/s/select-row-problem-68krr)

**Steps To Reproduce**

1. Click once in any checkbox
2. Nothing will appear
3. Scroll down so your row won't be rendered on DOM
4. Scroll back to the row you selected
5. Now the checkbox is checked

**Expected behavior**
When clicking any checkbox, it should be toggled to checked or not checked.

- OS: [Windows, MacOS]
- Browser [Chrome]
- Version [latest (?)]

**Comment by tannerlinsley** [comment]
This is because virtualized row components are memoized intensively out of the box. To get around this, you'll need to re-memoize your row renderer when anything used inside it is updated. In this case, `state` should do the trick:

<img width="407" alt="Screen Shot 2020-04-02 at 10 47 24 AM" src="https://user-images.githubusercontent.com/5580297/78275846-6896ff80-74cf-11ea-83fe-c315a701ef51.png">
