### ISSUE TITLE
[v6.11.5] Can't input when custom cell render

### ISSUE THREAD

**Issue by Cedcn** [tannerlinsley/react-table#2123]
**Describe the bug (required)**
Lost focus while typing in the input box,  (The reason may be that the cell is unmount and rerender. )

**Provide an example via Codesandbox! (required)**
https://codesandbox.io/s/modest-agnesi-ommn4

**Steps To Reproduce (required)**

1. Type in the input box

**Expected behavior (Recommended)**
   v6.10.0 is ok

**Desktop (please complete the following information):**
- OS:  ios
- Browser: Chrome
- Version: Any

**Comment by kizu** [comment]
This happens because you define the columns right inside your `<ReactTable />`. This makes React re-create it on each re-render and a change to the `columns` makes the `react-table` to recalculate things.

So moving it outside fixes this: https://codesandbox.io/s/blazing-haze-4vb6u?file=/src/index.js:346-367

**Comment by Cedcn** [comment]
@kizu Thanks. Because my columns will be changed with the props,  I need to adjust my code.
