### ISSUE TITLE
unique aggregation return [SetIterator] instead of array

### ISSUE THREAD

**Issue by rantibi** [tannerlinsley/react-table#2173]
**Describe the bug (required)**
Seems like the following `unique` premade aggregation not working well:
https://github.com/tannerlinsley/react-table/blob/master/src/aggregations.js#L70-L72

I have the following column:
```
{
    variety: 'x',
    Header: 'x',
    accessor: d => d.id,
    aggregate: 'unique',
    aggregateValue: 'unique',
    Aggregated: a => {
      const {
        cell: { value },
      } = a;
      console.log(value);
      return `${value}`;
    },
  },
```

when I check the log it prints [SetIterator] instead of the unique values as an array.

if I am doing the following it works as expected:

```
import { unique } from "react-table/src/aggregations";
...
{
    variety: 'x',
    Header: 'x',
    accessor: d => d.id,
    aggregate: unique,
    Aggregated: a => {
      const {
        cell: { value },
      } = a;
      console.log(value);
      return `${value}`;
    },
  },
```

https://codesandbox.io/s/laughing-pond-ieulg?file=/src/App.js

**Comment by tannerlinsley** [comment]
This is strange that it works with importing directly, but not as a string option

**Comment by thomasmarr** [comment]
@tannerlinsley I did a little digging on this today. The build process for react-table is converting

https://github.com/tannerlinsley/react-table/blob/f41b82d07deedaa75c48f259f9665c0ce614b679/src/aggregations.js#L71

to

`[].concat(new Set(values).values())`

The rescripts builder (used by the examples), does not make that conversion (which is why importing the function directly in the example App.js works, but importing it from the react-table bundle does not).

There is probably a way to configure rollup and/or babel not to make that conversion, but I'm not sure how. An alternative is just to use the slightly older fashioned syntax (which the rollup build process does not convert):

`Array.from(new Set(values).values())`

If you're happy with that approach I'll try and submit a PR tomorrow.

**Comment by tannerlinsley** [comment]
That would be great :)
