### ISSUE TITLE
Resizing on full width table

### ISSUE THREAD

**Issue by madaraszistvan** [tannerlinsley/react-table#2185]
While resizing the columns in [this](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/full-width-resizable-table?file=/src/App.js) example, the resizing does not follow the mouse (especially when in bigger screen).

I created a [video](https://youtu.be/JVa-st9QRXY) about this behaviour.

Device: MacOS, Browser: Chrome

**Comment by tannerlinsley** [comment]
This is intentional because of column flexing. Once column minimums or maximums are met on other columns, the resizing action will either diminish or increase as you resize.

**Comment by madaraszistvan** [comment]
I think the resizing should follow the mouse.

**Comment by tannerlinsley** [comment]
I would accept a PR to account for this though I assure you, it’s some very very complex math. I doubt it would be worth the effort or cover many edge cases. But still, you’re free to try.

**Comment by pavelspichonak** [comment]
@tannerlinsley current behavior it is not resizing of columns because when you make one column wider the other columns become more narrow. And yeah cursor is not following resize component.

I could fix it setting for each cell these styles:

`

    .th,
    .td {
      flex-grow: 0 !important;
      :last-child {
        flex-grow: 1 !important;
      }
`

Yeah resizer does not work for the last column and it is okay, just remove resizer from the last column.

[Here](https://codesandbox.io/s/ecstatic-leaf-ukci8?file=/src/App.js) you can see how it works.

Cursor is not following resize component only in one case, when your table is wider than container and you have horizontal scroll, and you scroll horizontally to the end and after that you try to resize(make **narrow**, **not** wider) any column. And this is expected behavior and you need I can explain why.

**Comment by austincondiff** [comment]
@pavelspichonak This almost works, but it makes the last column huge. We would need to set it only once it has been resized like this...
https://codesandbox.io/s/serene-browser-i0bjf?file=/src/App.js

The problem with this is, it jumps the set value which is much less than the flexed width upon first resize. Every subsequent resize is fine though. We would somehow need to efficiently get the width and set it on first resize. Any thoughts on how we might do this?
