### ISSUE TITLE
When column values are equal for all rows, rows order is changing by sorting

### ISSUE THREAD

**Issue by gegham1** [tannerlinsley/react-table#2188]
When column values are equal, rows order is changing.
I don't know if this is a BUG or not.
Is there is some way to prevent this behavior ?

**Codesandbox**
you can see this behavior in official example [react-table codesandbox](https://codesandbox.io/embed/github/tannerlinsley/react-table/tree/master/examples/sorting).

**Steps To Reproduce**
 - make firstName column value the same for all rows, and try to sort
![reproduce](https://user-images.githubusercontent.com/25671426/79568201-7ac78f00-80c6-11ea-9b13-981eb9b43566.jpg)

**Expected behavior**
If the values are equal, nothing need to be changed in rows order.

**Screenshots**
![sorting_1](https://user-images.githubusercontent.com/25671426/79568373-ca0dbf80-80c6-11ea-861f-19b62ea38735.jpg)
![sorting_2](https://user-images.githubusercontent.com/25671426/79568383-cd08b000-80c6-11ea-9534-8f16a44dba2b.jpg)

**Env**
- OS: windows
- Browser chrome
- Version 6.9.2

**Comment by ivaskevych** [comment]
It's not a bug, just a nature of the JS sort method - it's [unstable](https://en.wikipedia.org/wiki/Sorting_algorithm#Stability).

You can extend react-table sortTypes with your custom stable sorting function.

**Comment by tannerlinsley** [comment]
Actually, react-table's sorting **is stable**. This means that as a tie-breaker for values that are the same, the original index of the row is used as a fallback, so they will still invert, but consistently.

**Comment by xehpuk** [comment]
> It's not a bug, just a nature of the JS sort method - it's [unstable](https://en.wikipedia.org/wiki/Sorting_algorithm#Stability).

Spec:
>The elements of this array are sorted. The sort must be stable (that is, elements that compare equal must remain in their original order).

https://tc39.es/ecma262/#sec-array.prototype.sort

> Actually, react-table's sorting **is stable**. This means that as a tie-breaker for values that are the same, the original index of the row is used as a fallback, so they will still invert, but consistently.

Inverting means that the original order is changed => not stable. With this method you can't have a stable sort because the rows will never be regarded as equal.

This behavior violates the principle of least astonishment. _Microsoft Excel_ or _Google Sheet_ sort stably, for example.

More developers who were surprised: #913
Simple Sandbox: https://codesandbox.io/s/elated-resonance-u3xgk

Please reconsider.

**Comment by tannerlinsley** [comment]
@xehpuk, you've convinced me. Although, i still believe that inverting the stability should be an option. I will accept a PR to add this option and *not* invert the stability by default.

**Comment by xehpuk** [comment]
Relieved to hear this! 👍

This seems to be the line:
https://github.com/tannerlinsley/react-table/blob/3aa016e056b5e420b74134cb89f55ff296cda276/src/plugin-hooks/useSortBy.js#L373

It could look like this:
```js
return stableSort
  ? 0
  : dirs[0]
    ? rowA.index - rowB.index
    : rowB.index - rowA.index
```

But I'm not sure if this should really be a parameter of `orderByFn`. Wouldn't it be cleaner to abstract the sorting by making the `compareFn` customizable instead? And then do the `[...rows].sort(compareFn)`here:
https://github.com/tannerlinsley/react-table/blob/3aa016e056b5e420b74134cb89f55ff296cda276/src/plugin-hooks/useSortBy.js#L272

Like this:
```js
const sortedData = [...rows].sort((rowA, rowB) => {
  const sortInt = compareFn(rowA, rowB, funcs, dirs)
  return sortInt !== 0 || stableSort
    ? sortInt
    : dirs[0]
      ? rowA.index - rowB.index
      : rowB.index - rowA.index
})
```
And `defaultCompareFn` instead of `defaultOrderByFn`:
```js
export function defaultCompareFn(rowA, rowB, funcs, dirs) {
  for (let i = 0; i < funcs.length; i += 1) {
    const sortFn = funcs[i]
    const desc = dirs[i] === false || dirs[i] === 'desc'
    const sortInt = sortFn(rowA, rowB)
    if (sortInt !== 0) {
      return desc ? -sortInt : sortInt
    }
  }
  return 0 // stable by default
}
```
Then a custom `compareFn` wouldn't need to care about `stableSort`.

An alternative to the boolean `stableSort` prop would be the explicit inversion in a custom `compareFn`:

```jsx
const compareFn = (rowA, rowB, funcs, dirs) => {
  const sortInt = defaultCompareFn(rowA, rowB, funcs, dirs)

  return sortInt !== 0
    ? sortInt
    : dirs[0]
      ? rowA.index - rowB.index
      : rowB.index - rowA.index
} // emulate the old behavior

return (
  <Table columns={columns} data={data} compareFn={compareFn}/>
)
```
Or provide the function to make migration even easier.

But this would be kind of a breaking change. This is the first time I've looked into v7 so I don't know how *stable* the API is and if this would fit the general style of the project. Thoughts?

**Comment by thexpand** [comment]
@xehpuk Would you mind creating a PR for this or did you solve it with some workaround? There hasn't been an update for almost an year on this and I think it has been neglected for a long time now.

**Comment by xehpuk** [comment]
@thexpand I'm working on a different project now. We didn't solve it back then IIRC. Trying to create a PR is currently not feasible for me, sorry. Not sure why this is still closed though.

**Comment by thexpand** [comment]
@xehpuk Thanks for the quick response. I think I can create the PR myself, but not until Tanner gives his feedback on this. And for the time being I created a custom `orderByFn` that I pass to the custom hook, which I called `stableTableSort`, because it's a critical production bug that I need to fix for the client.

@tannerlinsley Please, review @xehpuk's comment and re-open this issue, as it is still not resolved.
