### ISSUE TITLE
Odd behaviour on column resize

### ISSUE THREAD

**Issue by theCmaker** [tannerlinsley/react-table#226]
## Problem Description
The last column does not stick on the right edge after resizing on several columns.

## Codepen 
The default Codepen can be used to reproduce the error:
http://codepen.io/tannerlinsley/pen/QpeZBa?editors=0010

## Steps to Reproduce
When resizing, please use the right edge of the given column.
1. Reduce the size of the first column,
2. Reduce the size of the second column,
3. Reduce the size of the third column.

Then, the last column does not stick anymore on the right edge of the table. And it is hard to find the sizing handle without a colored background.

When resizing the third column, the right behaviour would be for the two other columns to increase their size and fill the free space.

## System Information
* **Browser & Browser Version:** Chrome 58.0.3029.81
* **Node Version:** 6.10.0
* **OS Version:** Windows 7 Pro x64
* **NPM Version:** 4.4.1

**Comment by aaronschwartz** [comment]
This is currently expected behavior.

When you resize a column, it then becomes fixed width because you're controlling it's width manually. Once you resized all three columns, they all became fixed width and there were no more flex columns to take up the free space.

I do agree that it is hard to see the resize handle when all three columns have been resized smaller than the full width of the table. Maybe you could come up with some css to make the handles a little more obvious.

**Comment by theCmaker** [comment]
All right, thank you for your answer.

I made the handles easier to see. It is better now. But I am experiencing another strange behaviour.

In fact, I am trying to combine fixed column width with dynamic columns (one of these columns has a fixed width). I think it has a side effect on column properties. When I hide a column with a fixed width (let's say 40), then the next column width that should be "auto" is set to 40 (without specified width or resizing operation on this column).

The following code can be used as an example:
When you click on the show/hide button, the last column gets reduced. This is even worse when the third column has a fixed size instead of the second one. After hiding and showing again the second column, they have both the same fixed size.

```js
const ReactTable = window.ReactTable.default

let columns = [{
	header: 'First Name',
	accessor: 'firstName'
}, {
	header: 'Last Name',
	id: 'lastName',
	accessor: d => d.lastName,
	show : true,
	width: 200,
}, {
	header: 'Age',
	accessor: 'age'
}]

class MyTable extends React.Component {
	constructor(props) {
		super(props)
		
		this.state = {
			cols: props.cols,
		}
	}
	
	onToggleCol() {
		let {cols} = this.state
		cols[1].show = ! cols[1].show
		this.setState({cols: cols})
	}
	
	render() {
		return (
			<div>
				<h1>React-Table - Example with dynamically shown column</h1>
				<button onClick={this.onToggleCol.bind(this)}>Show/Hide <strong>Last Name</strong></button>
				<ReactTable
					data={makeData()}
					columns={this.state.cols}
					showFilters={true}
					pageSize={5}
				/>
				<br />
				<br />
				<h1>For more examples, <a href="https://react-table.js.org" target="_blank">see our react storybook</a></h1>
			</div>
		)
	}
}

ReactDOM.render(<MyTable cols={columns} />, document.getElementById('root'))



function makeData () {
	return [
		{
			"firstName": "judge",
			"lastName": "babies",
			"age": 16
		},
		{
			"firstName": "quarter",
			"lastName": "driving",
			"age": 17
		},
		{
			"firstName": "division",
			"lastName": "society",
			"age": 3
		},
		{
			"firstName": "lamp",
			"lastName": "point",
			"age": 2
		},
		{
			"firstName": "argument",
			"lastName": "insurance",
			"age": 13
		},
		{
			"firstName": "pets",
			"lastName": "fan",
			"age": 27
		},
		{
			"firstName": "learning",
			"lastName": "board",
			"age": 9
		},
		{
			"firstName": "observation",
			"lastName": "drink",
			"age": 28
		},
		{
			"firstName": "burst",
			"lastName": "glove",
			"age": 1
		},
		{
			"firstName": "acoustics",
			"lastName": "animal",
			"age": 19
		}
	]
}
```

**Comment by aaronschwartz** [comment]
That does look like a bug. I'll investigate.

**Comment by aaronschwartz** [comment]
It is caused by a bad key algorithm when looping through the columns. We're using the column index (in the array) for the `key` on the cell. 

Keys before hiding column: firstName: 0, lastName: 1, age: 2
Keys after hiding column: firstName: 0, age: 1

Since age now has a key of 1 React is deciding to reuse the existing cell which was the lastName cell before.

I'm a little surprised that React is doing that though since the array we're looping over is not the same array as before so I don't know why React would try and optimize this.

Making the key unique per column id does seem to fix it for me though. Maybe @tannerlinsley  has a better explanation.

**Comment by theCmaker** [comment]
Your patch in b026f8b seems to fix it for me too. Thank you very much for the explanation and that quick fix. :)

**Comment by tannerlinsley** [comment]
Yes, It should use a unique key from the columnID.

**Comment by mecampbellsoup** [comment]
@tannerlinsley 	@theCmaker 	probably not the right place to ask this but, is it possible to override the "resizable column header" behavior? I want a column header to act as a button but it seems like the resizing-on-hover is superseding it. 

It's the trash can in this screenshot:

![image](https://user-images.githubusercontent.com/2043821/63278200-dd853400-c274-11e9-9fdb-24d9ebd5e783.png)
