### ISSUE TITLE
Passing table instance down component tree via context breaks functionality

### ISSUE THREAD

**Issue by benknight** [tannerlinsley/react-table#2344]
**Describe the bug (required)**
Passing table instance down component tree via React Context breaks functionality.

**Provide an example via Codesandbox! (required)**
Here's a fork of the row selection demo sandbox, modified to use React context:
https://codesandbox.io/s/objective-kalam-iqw89?file=/src/App.js

**Steps To Reproduce (required)**

1. Go to sandbox
2. Click on checkboxes
4. Observe that checkbox state is not toggled on/off

**Expected behavior (Recommended)**
It should be possible to break large component trees up and pass the react-table instance via context.

**Additional context**
In a nutshell, I'm trying to do the following, with the goal of breaking my large table component into smaller pieces:

```jsx
const ReactTableContext = React.createContext({});

export default function Table({ children }) {
  const instance = useTable(
    {
      columns,
      data,
    },
    useFilters,
    useGlobalFilter,
    usePagination,
    useRowSelect,
  );
  return (
    <ReactTableContext.Provider value={instance}>
      {children}
    </ReactTableContext.Provider>
  );
}

export function TableRows() {
  const {
    getTableProps,
    getTableBodyProps,
    headerGroups,
    page,
    prepareRow,
  } = React.useContext(ReactTableContext);
  // Render rows...
}

export function TableFilters() {
  const {
    // ...
  } = React.useContext(ReactTableContext);
  // Render filters...
}

export function TablePagination() {
  const {
    // ...
  } = React.useContext(ReactTableContext);
  // Render pagination...
}

// Usage:
// <Table>
//   <TableFilters />
//   <TableRows />
//   <TablePagination />
// </Table>
```

**Comment by nderscore** [comment]
```jsx
<ReactTableContext.Provider value={instance}>
```
Your problem is here. `instance` is a stable reference, so you're passing the same value every time. Since it's the same value, the context never will update.

Easiest solve for this would be to create a new value object every time, with a reference to the instance:

```jsx
<ReactTableContext.Provider value={{ table: instance }}>
```

And to consume it like this:

```jsx
const { prepareRow } = React.useContext(ReactTableContext).table;
```

Or maybe add a helper:

```jsx
const useReactTableContext = () => React.useContext(ReactTableContext).table;
// ...
const { prepareRow } = useReactTableContext();
```

**Comment by benknight** [comment]
@nderscore thanks! I came up with my own fix shortly after posting this issue:

```jsx
// Before:
<ReactTableContext.Provider value={table}>

// After
<ReactTableContext.Provider value={{ ...table }}>
```

But I'm still wondering if this is the most performant approach as I expect most/all of my component tree will be rerendered on every update.

**Comment by tannerlinsley** [comment]
Rerenders are good and keep your app up to date with your UI state. Embrace them and just make them faster.

https://twitter.com/tannerlinsley/status/1255209957219168257
https://twitter.com/tannerlinsley/status/1255197677991522309

**Comment by mattleonowicz** [comment]
This lib behaviour is very counterintuitive in React ecosystem. It makes it impossible to effectively use this with any sort of memoization that you may have in place. Remembering to artificially create new references while passing any parts down may lead to many bugs.
I would suggest documenting this fact clearly in the docs.

**Comment by muhaimincs** [comment]
How to get the typescript working on this when declaring

```ts
const ReactTableContext = React.createContext({});
```

**Comment by HichemTab-tech** [comment]
I’m honestly **disappointed** after digging into the [React adapter source](https://github.com/TanStack/table/blob/e172109fca4cc403a07236ed8fa103450ceba5e9/packages/react-table/src/index.tsx#L69-L93).

I expected `getState()` (or the surrounding internals) to be doing something actually React-aware, like subscriptions, selectors, `useSyncExternalStore`, *anything* that ties state reads to component reactivity.

Instead, the React integration is basically doing this steps exactly:

* create a **stable** table instance once
* dump the **entire table state** into a single `useState`
* manually call `setState` on every `onStateChange`
* and rely on React re-rendering the whole subtree as a side effect (use a single React.memo and everything would break under the parent component).

That’s not reactivity. bruh.

What makes this especially disappointing is that the table instance ref is intentionally stable. State changes don’t affect identity, so correctness depends entirely on React re-rendering parents, and on users *not* memoizing too well.

Which is… great timing, considering the React Compiler.

With the compiler automatically injecting memoization, this design starts to look fragile at best. The implicit contract here feels like:

> “Please don’t let React optimize too aggressively, or the table might stop updating.”

OR the best part is suggesting something like:
```jsx
<Children table={{...table}}>
```
-_-

That’s a pretty disappointing place for a core data library to be in.

And I genuinely don’t understand why this issue is closed.

If anything, it should be resolved by a PR that adds a real subscription mechanism instead of a top-level `useState`, or at the very least the issue should stay open so someone else can explore a proper solution and contribute.

Closing it gives the impression that this isn’t a problem, when architecturally it clearly is.

Overall, I’m **disappointed** *because* TanStack is usually so good at this stuff. The quality of the tools is genuinely high, they’re flexible, well-thought-out, and powerful, **the TanStack Table core itself is great**. That’s exactly why looking at how the React adapter is implemented is so jarring. Compared to the elegance of the core, this feels like a shortcut that doesn’t live up to the rest of the ecosystem. I’m saying this with respect, but… the React adapter approach is a real “bruh” moment. I’d honestly love to see this revisited in a more React-native, subscription-based way, because the underlying library absolutely deserves it.

**Comment by riccardoperra** [comment]
@HichemTab-tech react adapter has been refactored in v9 (which is currently published as an alpha release) with a more idiomatic approach, taking inspiration from tanstack form. With the new api It should support both react compiler and passing instance down the tree
