### ISSUE TITLE
Expand groups by default

### ISSUE THREAD

**Issue by mpriem** [tannerlinsley/react-table#2404]
Hi @tannerlinsley,

react-table is great! I have been using it in various projects.  On one of my projects I have a initialstate.groupby and no ability to ungroup. I would however like to have the rows expanded by default. 

I was reading an earlier post: https://github.com/tannerlinsley/react-table/issues/1494 but cannot figure out how to implement it.
I would be very grateful if you provide some pointers on this?

Thanks!

Mark

**Comment by mmacaula** [comment]
@mpriem I've been experiencing the same issue.  The `expanded: true` doesn't seem to work when you use both `useGroupBy` _and_ `useExpanded`.  I traced this in the code to the fact that grouped rows don't have an 'original' property on them, where the code looks for the `expanded` attribute.  This kind of makes sense because they're grouped rows, just not clear in the docs. 

Anyways..  To fix this you have two options, you can create an 'expanded' object that has `true` for every row Id that is in your group.  How do you know your row id?  Well currently its the group by attribute followed by the pivot value.   It's definitely not easy.  The much easier way is to use some of the hooks that are present: 
```
  const { 
//... other props from useTable
toggleAllRowsExpanded,
    isAllRowsExpanded
 } = useTable(/**/)
// run an effect that expands all the rows and keeps them that way. 
  useEffect(() => {
    toggleAllRowsExpanded(true);
  }, [isAllRowsExpanded]);

```
This isn't a perfect solution, but it got me what I needed.  You can edit the dependencies or the interior of the `useEffect` to change the behavior as you see fit.  Hope that helps!

**Comment by mpriem** [comment]
Hey @mmacaula . Thanks for the response. I literally had the same solution in place. It works fine and also still have the ability to collapse rows. Thank again!

**Comment by nagiek** [comment]
This worked for me, thanks for your help!

`React.useEffect(() => toggleAllRowsExpanded(true), [toggleAllRowsExpanded]);`

**Comment by stahlmanDesign** [comment]
I was not able to get useEffect to work as described here, as a prop of useTable, but it does work when I use React.useEffect

However I see a warning so I wonder if I am doing it wrong:
` React Hook React.useEffect has a missing dependency: 'toggleAllRowsExpanded'. Either include it or remove the dependency array  `

**Comment by tannerlinsley** [comment]
@stahlmanDesign nailed it :)

**Comment by timothydowd** [comment]
Im trying to implement the above to have grouped rows expanded by default, however they are still closed unless manually triggered.  Whats interesting is that 'isAllRowsExpanded' is always false even when opening th grouped rows/columns..  

![image](https://user-images.githubusercontent.com/39065501/96293176-40da3580-0fe2-11eb-8f07-27d495a003c4.png)

**Comment by gsouf** [comment]
Something is still wrong, using `toggleAllRowsExpanded` won't expand groups for me. 

@tannerlinsley we have a method to open expand row on click via `row.getToggleRowExpandedProps()` why not having a method to expand groups in the table instance?

**Comment by zeorin** [comment]
For anyone that finds this via a Google search, what you actually want to do is to set `expanded: true` in the `initialState` of the options. Also consider setting `autoResetExpanded` to `false` so your rows don't collapse once the user starts changing the state of the table.

**Comment by fobos531** [comment]
> For anyone that finds this via a Google search, what you actually want to do is to set `expanded: true` in the `initialState` of the options. Also consider setting `autoResetExpanded` to `false` so your rows don't collapse once the user starts changing the state of the table.

Hey @zeorin , can you clarify there exactly should the `expanded: true` go? Maybe a small code snippet? Thanks!

**Comment by fobos531** [comment]
Works perfectly, thank you!

**Comment by petersamokhin** [comment]
@zeorin `expanded` initial state requires `expanded: Record<IdType<D>, boolean>;` and still doesn't work if you ignore the TS error

**Comment by KevinVandy** [comment]
> @zeorin `expanded` initial state requires `expanded: Record<IdType<D>, boolean>;` and still doesn't work if you ignore the TS error

If you are on V8, there should be no error. That's exactly how you are supposed to do it.
