### ISSUE TITLE
props.children in TrGroupComponent is sometimes react element, sometimes array?

### ISSUE THREAD

**Issue by terencechow** [tannerlinsley/react-table#247]
## Problem Description
I am making my `TrGroupComponent` return a react-router link and getting warnings in react saying its sometimes an array of react elements and sometimes a react element. Is this normal behaviour?

## Code Snippet(s) 
```
import {Link} from react-router
const addUrlProp = (state, rowInfo) => {
    if (rowInfo && rowInfo.row) return { to: `/${rowInfo.row.id}` }
    return { to: '' }
  }
const TrGroupComponent = (props) => <Link className='rt-tr-group' to={props.to}>{props.children}</Link>

//...somewhere later in a render function somewher

<ReactTable
    getTrGroupProps={addUrlProp}
    TrGroupComponent={TrGroupComponent}
     ...pass data and columns
/>
```

**Comment by aaronschwartz** [comment]
Can you post the exact warning message and/or recreate the warning on codepen.

It sounds like a warning coming from the Link component and not react-table.

**Comment by terencechow** [comment]
It is from react because I set proptype of children to expect a react
element. It's the standard react proptype warning when a proptype is not of
the same type as specified.  The question I have for you however is why the
child shows up as an array of react elements sometimes and just 1 react
element at other times.

**Comment by aaronschwartz** [comment]
Do you have pivoted columns or subcomponents?

TrGroupComponent will have multiple children (essentially an array) if you  have an expanded row.

**Comment by terencechow** [comment]
Nope don't use subcomponents

**Comment by aaronschwartz** [comment]
Hmm. What if you `console.log` the children?

**Comment by terencechow** [comment]
Yup I did. The array was length 3 with the first object being a react
element and the next 2 as undefined. It seems that it is only for rows with
data that it did the array of length 3 and 2 undefined. All other empty
rows were just 1 react element.

**Comment by aaronschwartz** [comment]
I take it back. The line I showed you creates child elements whether or not you have a subrow because even with a false conditional it creates an `undefined` element.

https://github.com/tannerlinsley/react-table/blob/master/src/index.js#L668

There is no way (that I'm aware of) to conditionally render an element without at the very least creating an `undefined` or `null` child element.

Subrows aren't ever needed in empty rows, so you don't have those conditional children in the empty rows.

Since this is the typical way of conditionally rendering element, I'm going to say that this is expected behavior you are seeing.

**Comment by tannerlinsley** [comment]
That is correct. We may change this in the future but for now this is the intended functionality
