### ISSUE TITLE
Event to resize columns should stop propagation

### ISSUE THREAD

**Issue by Paul-Yves** [tannerlinsley/react-table#281]
## Problem Description
If I have a react-table which is resizable on a drag&drop elements (or any element that listen to events for that matter), it gets triggered when I try to resize the a column, which can get quickly annoying.
Maybe a event.stopPropagation() could fix that.

## Codepen 
http://codepen.io/anon/pen/LyJpjJ?editors=0010

**Comment by tannerlinsley** [comment]
Yep, that needs to happen :) We'll get on it.

**Comment by tannerlinsley** [comment]
This is unfortunately impossible until the react event handling api's become more robust. Simply put, because we must listen for the cursor/touch up/end events at the document level (so you can drag anywhere on the screen to resize), the synthetic react event has actually already moved up the component tree to reach your onClick. The only way to possibly solve this would be to conditionally add fake up/end end events on every single react table component that would listen for this strange post-resize `onClick` event, stop its propagation, then remove the listener.

Unfortunately I've spent the last 3 hours trying to solve this using the above method and many others with no avail.  It appears there are many other devs who are disappointed in this edge case with react. :(

**Comment by vrathnayake** [comment]
Yes, this would be a nice feature if there is any possibility.

**Comment by aaronjones1** [comment]
Can't you do this?

```tsx
// ...
<tbody>
  {table.getRowModel().rows.map((row) => (
    <tr
      key={row.id}
      onClick={(e) => {
        e.stopPropagation(); // 🫷
        return row.getToggleSelectedHandler()(e);
      }}
    >
// ...
```

Or am I misunderstanding the situation?
