### ISSUE TITLE
Scroll to index

### ISSUE THREAD

**Issue by cdtinney** [tannerlinsley/react-table#299]
This is a feature request.

I have a use case where a certain row is selected initially, and it's being styled differently.

It would be helpful to be able to jump to a specified index that forces the table to scroll down to ensure that row is visible.

**Comment by tannerlinsley** [comment]
The scrolling in react-table is nothing special, it's a simple `overflow: scroll` css rule.  Other than that react-table doesn't support any complex scrolling operations out of the box.  This would be something you would need to work on as a customization on your own, since React-Table doesn't technically support infinite-scrolling, or any other complex sorting operations. If you want to run any ideas by the team to figure out how to do this within the current table api, please join the slack community :)
