### ISSUE TITLE
defaultExpanded does not work with pivotBy

### ISSUE THREAD

**Issue by geowarin** [tannerlinsley/react-table#306]
As a foreword, thanks for react-table, it's awesome :smile: 

## Problem Description

When using `pivotBy`, `defaultExpanded` has no effect.
(always undefined [here](https://github.com/tannerlinsley/react-table/blob/master/src/index.js#L446))

## Repro

https://codepen.io/anon/pen/rmEqmx?editors=0010

## Current workaround

The controlled prop `expanded` seems to work so we can use that in conjugation with `onExpandedChange` to make it work as expected.

**Comment by tannerlinsley** [comment]
Af first look, this appears to be a bug. We'll get on this asap.

**Comment by alex-bashkatov-ezlo** [comment]
@geowarin Hi, how do you define expanded properly?
Let's say I have 4 rows and they're grouped into 1 by some column. So, I should have
```js
expanded={0: true}
```
not
```js
expanded={0: true, 1: true} // and so on
```
Thanks in advance

**Comment by geowarin** [comment]
@alex-bashkatov-ezlo :

```js
expandedRows: {
      0:
        {
          0: true,
          1: true,
          2: true
        }
    }
```

I agree the syntax is a bit confusing

**Comment by ernani** [comment]
I have a table with pivotBy enabled, how do I use defaultExpanded to return all dynamic columns as expanded? Can't seem to find a good example on it.

**Comment by gary-menzel** [comment]
The best place to start would be to grab the prop in an `onExpandedChange` handler and have a look at what the structure is like.  But, ultimately, you'll have to get `ref` to the component and grab the state by calling `getResolvedState()` on the `ref` and then use the `sortedData` element in the state to walk the tree to get all the `viewIndex` props to create the nested structure.

Since this issue was written, the github issues are now for reporting bugs and requesting features. So this question is best asked over on the #react-table Slack channel (badge on the top of the README in the doco) as there are more people there to provide advice. Thanks.

**Comment by ernani** [comment]
Thanks for replying and sorry to use this to ask questions, I've missed the slack part, will be joining there soon! Again, thanks a bunch! I will close this issue!
