### ISSUE TITLE
Styling filter input doesn't have an affect

### ISSUE THREAD

**Issue by cbll** [tannerlinsley/react-table#343]
Attempting to style the input from the column:

```
        const swColumn = [
            {
                header: "Software Information",
                id: 'software',
                filterable: true,
                accessor: 'text',
                filter: cellInfo => (
                    <Input icon='search' placeholder='Search...' />
                )
            }
        ];
```

Using semantic-ui-react Icon.. It's rendered elsewhere(in normal input boxes), but doesn't seem to apply itself here. Do I need to somehow bind the div to the cellInfo attribute we're passing?

Is there an example of how do style the input boxes?

**Comment by tannerlinsley** [comment]
If `Input` is a custom react element, this should work just fine, since the rendering of that element is passed to react. Closing for triage. If you would like to discuss this more, please join the slack chat :)
<a href="https://react-chat-signup.herokuapp.com/" target="\_parent">
  <img alt="" src="https://img.shields.io/badge/slack-react--chat-blue.svg" />
</a>
