### ISSUE TITLE
When columns don't fit in width, the vertical scroll gets hidden inside div

### ISSUE THREAD

**Issue by shippin** [tannerlinsley/react-table#382]
## Problem Description
I have a table with many columns, and I want to be able to scroll Horizontally to see them, but keep the vertical scroll also visible - And not hidden inside the div.

## Code Snippet(s) or Codepen:
Please see screencast here:
[See video](https://youtu.be/poyc4dK3stw)

## Steps to Reproduce
1. Use many columns so they don't fit horizontally
2. you will see the vertical scroll gets hidden.
(see here: https://youtu.be/poyc4dK3stw )

**Comment by lord-xeon** [comment]
I am also encountering this problem, I'm looking at a fix in CSS if possible.

**Comment by tannerlinsley** [comment]
I'll look into this

**Comment by tannerlinsley** [comment]
This is unfortunately, something we cannot avoid right now due to the layout architecture of the table. Doing so would be a choice between horizontal scroll syncing (having the column headers follow you as you scroll horizontally) or what you are describing.  In the very distant future, there is the possibility we move to a synced layout (which would allow for this functionality and other features like column pinning), but for now, there are no plans to support this yet.

**Comment by shippin** [comment]
Thanks for looking into this.

**Comment by junbinku** [comment]
Is this issue have been implemented yet? Im not sure how to fix this where my react table scroll just disappear

**Comment by mjoyce91** [comment]
Might not be the most elegant solution, but I used [react-repeatable](https://github.com/cheton/react-repeatable) with a jquery function to scroll the table body with a custom component.

```js
function scrollContent(direction, className) {
  if (direction === 'up' || direction === 'down') {
    const amount = (direction === 'up' ? '-=100px' : '+=100px');
    $(`.${className}`).animate({
      scrollTop: amount,
    }, 1, () => {
    });
  }
}
```

![jun-14-2018 08-12-51](https://user-images.githubusercontent.com/11576347/41411417-cb54ebea-6faa-11e8-9d21-6cb188bf8001.gif)

I'd imagine a custom scroll bar component could be used as well, this just worked for my needs.
