### ISSUE TITLE
accessing row.original from a pivoted row

### ISSUE THREAD

**Issue by ericmcgregor** [tannerlinsley/react-table#393]
I'm having a hard time controlling the Pivot feature.  I have a pretty simple example, where I would like to pivot by the list of clients, and then see the names of the products underneith.  It's pretty straightforward getting to that point (pivotby={['client', 'name']}), however i'd like to include a link to the product by it's id.  

Since I'm not aggregating names, I'm using the "Pivot" key on the column.  that should pass in the 'row', but when i go to wrap the name with a link using the row.original.id as the href... it turns out that row.original is undefined.

could you help me understand what i'm doing wrong?  I couldn't find a good example of controlling the pivoted rows.

**Comment by tannerlinsley** [comment]
In an aggregated (pivoted) row, there technically is no single `original` row, since it is some aggregation of multiple rows resulting from the pivot. However, the props you are given in a pivoted renderer include `subRows`, which you can use to get at an original value for any of the rows in that pivot group.
<img width="167" alt="screen shot 2017-07-31 at 8 55 24 am" src="https://user-images.githubusercontent.com/5580297/28783584-0c0acc36-75ce-11e7-908a-a8a3a8f00bdd.png">
