### ISSUE TITLE
Page Index Resets?

### ISSUE THREAD

**Issue by JHRms** [tannerlinsley/react-table#411]
When I am handling server-side data and moving from page 1 to page 2, the page index resets to 1 every time. Any ideas why this could happen?

**Comment by tannerlinsley** [comment]
When using server-side data, there is only one page of data present in the table at a time. You must set the `page` prop to the page index you are displaying.

**Comment by JHRms** [comment]
Is there a reason why `page` does not need to be displayed in the detailed Server-Side Data Example? There is a `pages`, but not a `page`.

**Comment by tannerlinsley** [comment]
In the example, there is no `page` prop, which means react-table will manage the state for the current page internally. When the Next button is clicked for example, the internal `page` index is incremented, then `onFetchData` is called with the new state. `pages` is something that cannot be managed internally by react-table, since it is information only the server knows about (since you are only displaying one page of data at a time). For this reason, you can optionally return a `pages` number to let react-table know how many pages are on the server for the given query.

**Comment by JHRms** [comment]
I am still a bit confused. Initially, I set the page to 0. When I fetch the data, I set a store value for page to be the new index. However, it doesn't seem to change. Am I doing something wrong here?

`<ReactTable
     ...
      pages={ store.getState().pages }
      page={ store.getState().page }
      manual
      onFetchData={(state, instance) => {
        DocumentActions.fetchDocs(state.pageSize, state.page, state.sorted, state.filtered);
      }}`

**Comment by tannerlinsley** [comment]
If you are using the `page` prop, then you would also need to use the `onPageChange` prop. Otherwise the page would always equal `store.getState().page`

```javascript
...
page={store.getState().page}
onPageChange={newPage => DocumentActions.setPage(newPage)}
...
```

**Comment by kwallace50** [comment]
In following the example given above I'm running into the same issues, there seems to be a bit of a race condition when storing the page value in React setState. 

`
...
page={this.state.page}
onPageChange={pageIndex => this.setState({page: pageIndex})}
onFetchData={(state, instance) => {getData(state.pageSize, state.page)}}
...
`

When onFetchData gets call, setState has not finished updating the `this.state.page` value yet. Any ideas on what's going on?

**Comment by sonlexqt** [comment]
I'm having the same issue, hopefully this issue will be re-opened

**Comment by elcolie** [comment]
@kwallace50 I got the same problem. So the `pageIndex` got reset back to first value again and again. When I tried to set the value it will recursively change the state.

Any update on this?

**Comment by risaac** [comment]
I'm having the same issue, any help will be much appreciated.

**Comment by maxtotheguenther** [comment]
Me as well. someone could bypass the problem?

**Comment by elcolie** [comment]
@maxtotheguenther The widget itself is designed to do eager load. If you are going to do server pagination, you'd better hack a bit. Please let me know that you have a `PR` on this. For I myself I bypass by do eager load.

**Comment by JoshMcCullough** [comment]
So is this not fixed, then? But it's closed...

**Comment by JoshMcCullough** [comment]
If we are storing page/sort/etc. params in URL, and a user browses back (via the browser's back button) to our page with `page=1` in the querystring, is there no way to properly pass this value to react-table in a way that will work correctly?

Currently when we pull `page=1` from the querystring, pass it through to react-table and set it as `page={page}`, it still immediately fires off `onFetchData` with `state.page` set to `0`. So we immediately query page 0's data (which we don't need), and then clobber the page value in the querystring since we're relying on react-table to be the source of truth for paging and sort parameters. 

So it seems that react-table fires `onFetchData` before its state has even been initially set. Any ideas?

**Comment by qingmulanyun** [comment]
Any update on this issue?

**Comment by qingmulanyun** [comment]
To people who's using `useTable` hook, when using server-side data,You must set the `pageIndex` of `initialState` to the page index you are displaying.
Since `pageIndex` will be default as 0 if you don't set it. Every time you query data from server side it will rerender whole table page with new data and 

```
initialState: {
        pageIndex: #pageIndex,
        pageSize: #pageSize,
      },
```
So if you don't set that pageIndex a dynamic value, it will rerender to its default value 0.

All overall, something like this:

```
= useTable(
    {
      columns,
      data,
      initialState: {
        pageIndex: controlledPageIndex,
        pageSize: 50,
      },
      manualPagination: true,
      pageCount: controlledPageCount,
    },
    usePagination
  )
```

`controlledPageIndex` is a prop from parent component.

**Comment by GnaneshKunal** [comment]
Adding to the above comment, we should also set `autoResetPage` to `false` in order to prevent the table getting reset after the data has changed.

```diff
= useTable(
    {
      columns,
      data,
      initialState: {
        pageIndex: controlledPageIndex,
        pageSize: 50,
      },
      manualPagination: true,
      pageCount: controlledPageCount,
+     autoResetPage: false,
    },
    usePagination
  )

```

**Comment by jagarkin** [comment]
> Adding to the above comment, we should also set `autoResetPage` to `false` in order to prevent the table getting reset after the data has changed.
> 
> ```diff
> = useTable(
>     {
>       columns,
>       data,
>       initialState: {
>         pageIndex: controlledPageIndex,
>         pageSize: 50,
>       },
>       manualPagination: true,
>       pageCount: controlledPageCount,
> +     autoResetPage: false,
>     },
>     usePagination
>   )
> ```
 this worked for me thank you

**Comment by SomnathKadam** [comment]
> initialState: {
>         pageIndex: controlledPageIndex,
>         pageSize: 50,
>       },
>       manualPagination: true,

In version 8, it is `autoResetPageIndex: false,` instead of `autoResetPage: false`

**Comment by oakis** [comment]
Crazy how `autoResetPageIndex` is set to `true` by default, or am i missing something?

**Comment by Zac-Zajdel** [comment]
100% agree @oakis. I started looking into Github issues assuming this was a bug. For the majority of any true applicable use case, this should be set to `false` by default.

**Comment by mleenhardt** [comment]
> Crazy how `autoResetPageIndex` is set to `true` by default, or am i missing something?

It does indeed seem to be set to true whether you use server rendering or not. I also just spent hours trying to figure out why the pagination state was getting reset on the last render before trying to set `autoResetPageIndex: false`, which made the issue go away. I'm using 8.11.7.

**Comment by tmaihoff** [comment]
you guys saved my day....

I was troubleshooting for hours trying to understand why it jumped back to the initial page after setting a page. Weird out-of-the-box behaviour

**Comment by ahmednabik** [comment]
This should be `false` by default. Why would someone want to jump back to page 1 after they change/update some row data on page 5? weird. Thank you @GnaneshKunal  for saving me time.

**Comment by akashutosh77** [comment]
I am not doing manual pagination and I am using useMaterialReactTable hook, still I am facing the same issue.

```
export const useMaterialReactTableConfig = (columns, data, isLoading, pageSize ) => {
  return useMaterialReactTable({
    columns,
    data,
    state: { isLoading },
    enableColumnResizing: false,
    enableFullScreenToggle: false,
    initialState: {
      density: "compact",
      pagination: {
        pageSize: pageSize,
        pagination: { pageSize: 10, pageIndex: 0 },
      },
    },
    renderEmptyRowsFallback: () => <NoData />,
    muiTableBodyProps: {
      sx: {
        "& tr:nth-of-type(odd)": {
          backgroundColor: "#f5f5f5",
        },
      },
    },
    muiTableContainerProps: {
      sx: { maxHeight: "500px", boxShadow: "none", borderRadius: 0 },
    },
    muiTablePaperProps: {
      sx: {
        boxShadow: 0,
        borderRadius: 0,
        height: "100%",
      },
    },
  });
}

  const columns = useMemo(() => getAttendanceColumns(setData), [setData]);

  const table = useMaterialReactTableConfig(columns,data,isLoading, pageSize);

<MaterialReactTable table={table} />
```

**Comment by Cristy94** [comment]
I am facing the same issue, I simply want to load directly on page 2 (I get it from query params).

I tried everything, but the page index somehow gets reset to zero:

Even with this:
```
        autoResetPageIndex: false,
        initialState: {
            pagination: { ...pagination, pageIndex: 2 },
        },
        state: {
            pagination: { ...pagination, pageIndex: 2 },
        },
```

In the end it shows page 2, but, it first shows page 2, then loads data and shows page 1 (index 0), then back to 2, and the selected page is also wrong in the page number selector.

EDIT: Thinking about it, it might be because the table doesn't have data initially, so before any data is loaded the page will be zero (?)

**Comment by Cristy94** [comment]
Ok, so I fixed the issue in my case by tracking the initial load (I was not using the table isLoading state).

The problem is that if the table is rendered without data, it resets the page index to 0 (UNLESS isLoading is true).

Now I set this:

```
        const firstLoad = useRef(true); 

        // I set this to false after first data fetch is complete
        firstLoad.current = false;

        [...]
        // useMaterialReactTable
        state: {
            isLoading: firstLoad.current
        },
```
