### ISSUE TITLE
Can not implement prop onPageChange

### ISSUE THREAD

**Issue by trangtv04110** [tannerlinsley/react-table#65]
Hi, I'm using react-table, I want to save pageIndex.
So, I use prop onPageChange={(pageIndex) => { console.log('ABC'); }}, but it doesn't works.
Please help me

`<ReactTable
          loading={false}
          data={ this.state.data }
          columns={columns}
          showPageJump={false}
          showPageSizeOptions={false}
          pageSize={30}
          onPageChange={() => { console.log('ABC'); }} />`

**Comment by tannerlinsley** [comment]
`onPageChange` should work just fine in the latest version: https://github.com/tannerlinsley/react-table/blob/master/src/componentMethods.js#L297-L300

However, if you're looking to only monitor the page changing instead of managing the page changes, you may just want to subscribe using the `onChange` prop:

```javascript
onChange={(state, instance) => { console.log(state.page) }}
```

**Comment by tannerlinsley** [comment]
Does this work for you @trangtv04110 ?

**Comment by trangtv04110** [comment]
@tannerlinsley You are right. 
Using onChange prop, it works good.
Thank you so much.
