### ISSUE TITLE
i'm not sure how to handle server side data fetching..

### ISSUE THREAD

**Issue by mikedevita** [tannerlinsley/react-table#8]
right now i use redux and pull a list of users into props and drop it into ReactTable like so.. i use Immutablejs and store them in a `users.results` store hence `users.get('results')`

```javascript
<ReactTable
    tableClassName='table table-striped'
    data={users.get('results')}
    columns={_columns}
/>
```

the backend returns data like so in a paged format (using sailsjs)

```json
{
  "code": "OK",
  "message": "Operation is successfully executed",
  "data": [
    {
      "groups": [
        {
          "name": "Users",
          "accessLevel": 1,
          "id": 2,
          "createdAt": "2016-10-24T20:37:50.889Z",
          "updatedAt": "2016-10-24T20:37:50.889Z"
        }
      ],
      "username": "GarretKertzmann57",
      "email": "Enid96@gmail.com",
      "firstName": "Dangelo",
      "lastName": "Muller",
      "photo": "",
      "accountType": "local",
      "id": 1,
      "createdAt": "2016-10-24T20:37:51.592Z",
      "updatedAt": "2016-10-24T20:37:52.201Z"
    }
  ],
  "criteria": {},
  "limit": 20,
  "start": 0,
  "end": 20,
  "page": 0
}
```

and the api code in react looks like this to handle the fetching of data, yet im not sure how to go about handling this so ReactTable can fetch the data for me. Would you be able to provide a working example of getting the code to work? `Api.get()` is a middleware I wrote which wraps `axios`.

```javascript
export const find = (params = {}, payload = {}) => {
  return (dispatch, getState) => {
    return new Promise((resolve, reject) => {
      dispatch(getUsers({ ...params, payload }))
      log.debug('Users::find::initial', params, payload)
      Api.get('/users', { auth: true, populate: ['groups'] }, payload)
      .then((response) => {
        log.debug('Users::find::success', params, payload, response)
        return response
      })
      .then(({ data }) => {
        dispatch(gotUsers(data))
        resolve(data)
      })
      .catch((err) => {
        log.error(err)
        if (err.status === 401) {
          dispatch(Notification.emit({
            msg: err.data.message,
            visible: true,
            dismissable: true,
            type: 'error'
          }))
          dispatch(errorReceivingData(err))
        }
      })
    })
  }
}
```

**Comment by tannerlinsley** [comment]
If you are using redux, then there a few ways you can go about it:

1. Just get your data to your render function like you normally would with redux.  Request it using any asynchronous means, and as long as it ends up in your state, you can connect it to your component props through the redux connect function and then just synchronously feed the data into `<ReactTable data={myData} />`. No need to overcomplicate things.

2. If you want to use React-Table to fetch your data (especially server-side paginated and sorted data), then use a function instead of an array like so:

```javascript
<ReactTable
  columns={...}
  data={(params, callback) => {

    Users.get('id')
    .then((res) => {
      callback({
        rows: [...]
      })
    })

  }}
/>
```

All this function does is tell React-Table to show a loading message until you either:
- Return a promise that resolves an object with the rows, or
- Pass the `callback` an object with rows (which is what I do in the example above)

I myself use both methods to get different things done in my apps.  

The first method of using data out of redux is very easy for showing crud objects I already have in my redux store.  If they need to be fetched, then I fetch them, and update the store, eventually just rendering the data into ReactTable synchronously. Also with all of the data in ReactTable, it can handle all of the sorting and pagination for you client-side.

The second method honestly is mainly for using server-side pagnination and sorting. I use it in some components where I don't necessarily need the data I'm requesting to live in redux state, so I simply request it asynchronously in the `ReactTable` data method, and let the server return what it wants.

My last piece of advice would be, If you aren't using server-side pagination or sorting, then just pipe your data directly into ReactTable as opposed to using the callback. I hope this clears things up.  If not, you should join the slack channel and we can talk more about your specific implementation.

https://react-table-slack.herokuapp.com/

**Comment by mikedevita** [comment]
Yeah it's for crud stuff I use mapdispatchtoprops so findUsers() is a map to Users.find() just named differently. I'll try your implementation shortly thanks!

**Comment by tannerlinsley** [comment]
You bet. I'm on slack right now if you need more help.  Closing for now.
